export const m = {
  paper: '#F4F4F6',
  surface: '#FFFFFF',
  ink: '#232329',
  muted: '#87878F',
  line: '#E7E7EB',
  accent: '#6B6FB5',
  accentInk: '#565A9E',
  accentSoft: '#ECECF6',
  danger: '#B4453C',
  dangerSoft: '#fbecea',
  radius: 20,
  radiusSm: 12,
  shadow: {
    soft: {
      shadowColor: '#232329',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.05,
      shadowRadius: 16,
      elevation: 2,
    },
    lift: {
      shadowColor: '#232329',
      shadowOffset: { width: 0, height: 20 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 4,
    },
  },
  fonts: {
    display: 'HankenGrotesk_600SemiBold',
    displayBold: 'HankenGrotesk_700Bold',
    displayRegular: 'HankenGrotesk_400Regular',
    body: 'Inter_400Regular',
    bodyMedium: 'Inter_500Medium',
  },
  wrap: 1080,
};
